# These are supported funding model platforms

patreon: rexogamer
ko_fi: rexogamer0035
custom: ["https://paypal.me/rexo1183", "https://ko-fi.com/quantumlytangled", "https://patreon.com/quantumlytangled"]
