name: Make Docker Container for Development
 
on:
  workflow_dispatch:
  push:
    branches:
    - build

jobs:
  Contain:
    name: 'Create Docker Container for Development'
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip build]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
        with:
          ref: build
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --ignore-scripts --frozen-lockfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: Devnol 
          password: ${{ DEVNOL_CR_PAT }} #TODO: if this doesn't work we'll just use a specific PAT
      - name: Build and push to ghcr
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            terrific-tea/Debia:dev-latest
            terrific-tea/Debia:${{ github.run_number }}
            ghcr.io/terrific-tea/Debia:dev-latest
            ghcr.io/terrific-tea/Debia:${{ github.run_number }}
