name: Make Docker Container for Development
 
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: 
      - main
    types: 
      - completed
      - requested
  push:
    branches:
      - build
jobs:
  Contain:
    name: 'Create Docker Container for Development'
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip build]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
        with:
          sha: build
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --ignore-scripts --frozen-lockfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Devnol
          password: ${{ secrets.DEVNOL_CR_PAT }}
      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/cytrus-re/debia:dev-latest
            cytrus-re/debia:dev-latest
            ghcr.io/cytrus-re/debia:${{ github.sha }} 
            cytrus-re/debia:${{ github.sha }}