name: Build and Deploy to Google Compute Engine Test

on:
  push:
    branches:
    - main

env:
  GCE_INSTANCE: debia-server
  GCE_INSTANCE_ZONE: us-west1-b
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  EXTERNAL_IP: ${{ secrets.EXTERNAL_IP }}

jobs:
  gce-deploy:
    name: Deploy code to gce
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      
    - name: Setup gcloud CLI 
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    - name: Install python and pip
      run: sudo apt update && sudo apt install python python-pip -y

    - name: Install cloud client libraries for python
      run: pip install --upgrade google-api-python-client

    - name: Download sample app
      run: curl -O https://raw.githubusercontent.com/GoogleCloudPlatform/python-docs-samples/master/compute/oslogin/service_account_ssh.py
    
    - name: Run sample app
      run: | 
        python service_account_ssh.py \
        --cmd 'sudo apt install cowsay -y && cowsay "It works for real this time!"' \
        --project $PROJECT_ID \
        --hostname $EXTERNAL_IP
        
        



        
