name: Build and Deploy to Google Compute Engine Test

on:
  push:
    branches:
    - main

env:
  EXTERNAL_IP: ${{ secrets.EXTERNAL_IP }}
  SA_NAME: ${{ secrets.GCE_SA_NAME }}
  SSH_KEY: ${{ secrets.SA_SSH_KEY }}
jobs:
  gce-deploy:
    name: Deploy code to gce
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      
    - name: Setup gcloud CLI 
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    - name: Run debug info
      run: |
gcloud auth list

    - name: Generate ssh key from secret
      run: echo $SSH_KEY > ./SSH_KEY

    - name: Connect to server and run test
      run: ssh -i ./SSH_KEY $SA_NAME@$EXTERNAL_IP "echo yeet > test.txt"