name: Build and Deploy to Google Compute Engine Test

on:
  push:
    branches:
    - main

jobs:
  gce-deploy:
    name: Deploy code to gce
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      
    - name: Setup gcloud CLI 
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
    
    - name: Install Python and pip
      run: sudo apt update && sudo apt install python python-pip -y

    - name: Install Cloud Client Libraries for Python
      run: pip install --upgrade google-api-python-client

    - name: Obtain Sample App
      run: curl -O https://raw.githubusercontent.com/GoogleCloudPlatform/python-docs-samples/master/compute/oslogin/service_account_ssh.py

    - name: Export Service Acount Key to json file
      run: echo ${{ secrets.GCE_SA_KEY }} > ./sa_key.json

    - name: Connect to server and run test
      run: | 
        export GOOGLE_APPLICATION_CREDENTIALS="./sa_key.json"
        python service_account_ssh.py \
        --cmd 'echo test > test.txt' \
        --account ${{ secrets.GCE_SA_NAME }} \
        --project ${{ secrets.GCE_PROJECT }} --hostname ${{ secrets.GCE_EXTIP }}


      